version: '3' 
services:
  web:
    container_name: appflask
    restart: always
    image: flaskapp
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
        - db
    depends_on:
        - db
  db:
    container_name: sqlflask
    restart: always
    image: sqlflask 
    volumes:
        - .:/home/chuck/db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 'dipto'
      MYSQL_DATABASE: 'product'
    ports:
      - "3306:3306"