version: '3' 
services:
  web:
    container_name: appflask
    restart: always
    image: diptochakrabarty/api:appv1
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
        - db
    depends_on:
        - db
  db:
    container_name: sqlflask
    restart: always
    image: diptochakrabarty/api:dbv2
    volumes:
        - .:/home/chuck/db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 'dipto'
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_DATABASE: 'product'
    ports:
      - "3306:3306"