version: '3' 
services:
  web:
    container_name: appflask
    image: flaskapp
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
        - db
    depends_on:
        - db
  db:
    container_name: sqldb
    image: mysql
    volumes:
        - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dipto
    ports:
      - "3306:3306"