apiVersion: apps/v1
kind: Deployment
metadata:
    name: flaskapp
    labels:
        app: api 
spec:
    replicas: 3
    selector:
        matchLabels:
            app: api 
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - image: flaskapp:latest
                  name: api-app
