apiVersion: apps/v1
kind: Deployment
metadata:
    name: flask-app
    labels:
        app: api 
spec:
    replicas: 3
    selector:
        matchLabels:
            app: api 
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - image: diptochakrabarty/api:appv1
                  name: api-app
                  ports:
                    - containerPort: 5000
                  imagePullPolicy: Always
