apiVersion: v1
kind: Service
metadata:
    name: flaskapp
spec:
    selector:
        app: api 
    ports:
        - port: 80
          targetPort: 5000
          protocol: TCP
    type: LoadBalancer
