apiVersion: app/v1
kind: Deployment
metadata: 
    name: mysql-db
spec:
    selector:
        matchlabels:
            tier: db
    template:
        metadata:
            name: mysql-db
            labels:
                tier: db
        spec:
            containers:
                - name: sqlflask
                  image: sqlflask
                - env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: app-secrets
                            key: password
                   

            